import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const preferences = sqliteTable('preferences',{owner:text('owner').primaryKey(),payload:text('payload').notNull()});
export const sessions = sqliteTable('sessions',{owner:text('owner').notNull(),id:text('id').notNull(),startedAt:text('started_at').notNull(),payload:text('payload').notNull(),digest:text('digest').notNull()},t=>[primaryKey({columns:[t.owner,t.id]}),index('sessions_owner_date').on(t.owner,t.startedAt)]);
export const devices = sqliteTable('devices',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),tokenHash:text('token_hash').notNull().unique(),lastSeen:integer('last_seen').notNull(),createdAt:integer('created_at').notNull()},t=>[index('devices_owner').on(t.owner)]);
export const pairing = sqliteTable('pairing',{codeHash:text('code_hash').primaryKey(),owner:text('owner').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('pairing_owner').on(t.owner)]);
export const rateLimits = sqliteTable('rate_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expiresAt:integer('expires_at').notNull()});
export const accounts = sqliteTable('accounts',{id:text('id').primaryKey(),provider:text('provider').notNull(),providerSubject:text('provider_subject').notNull().unique(),email:text('email'),name:text('name'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()});
export const authSessions = sqliteTable('auth_sessions',{id:text('id').primaryKey(),accountId:text('account_id').notNull(),expiresAt:integer('expires_at').notNull(),createdAt:integer('created_at').notNull(),userAgent:text('user_agent')},t=>[index('auth_sessions_account').on(t.accountId)]);
export const qrClaims = sqliteTable('qr_claims',{nonceHash:text('nonce_hash').primaryKey(),deviceId:text('device_id').notNull(),accountId:text('account_id').notNull(),claimedAt:integer('claimed_at').notNull()});
